# Quantumult X 配置片段
# JD 京豆资产查询（仅查询本设备登录账号）
# Author: z.W.

[task_local]
0 9,20 * * * https://raw.githubusercontent.com/5jwoj/BeRich/main/JDCK/JD_Bean_Query_QX.js, tag=京豆资产查询, img-url=https://raw.githubusercontent.com/Orz-3/mini/master/Color/jd.png, enabled=true
