[rewrite_local]
# 1) 抓包重写: 匹配微信内置打开小阅阅链接时抓取 Cookie 和 UnionID
^https?:\/\/.*\/xiaoxinxin\/ url script-request-header https://raw.githubusercontent.com/5jwoj/BeRich/main/xyy/xyy_qx.js

[task_local]
# 2) 定时任务: 每天 6:15, 8:15, 10:15, 12:15, 14:15, 16:15 自动阅读
15 6,8,10,12,14,16 * * * https://raw.githubusercontent.com/5jwoj/BeRich/main/xyy/xyy_qx.js, tag=小阅阅全自动阅读, img-url=https://raw.githubusercontent.com/Orz-3/mini/master/Color/wechat.png, enabled=true

[mitm]
hostname = *.info, *.asia, *.9d0hl2.info, *.ohqnjl.asia
