[rewrite_local]
# 1) 抓包重写: 匹配微信内置打开小阅阅链接时抓取 Cookie 和 UnionID
^https?:\/\/.*\.asia\/xiaoxinxin\/ url script-request-header https://raw.githubusercontent.com/5jwoj/BeRich/main/xyy/xyy_qx.js

[task_local]
# 2) 定时任务: 每天 7:15, 12:15, 18:15 自动阅读
15 7,12,18 * * * https://raw.githubusercontent.com/5jwoj/BeRich/main/xyy/xyy_qx.js, tag=小阅阅全自动阅读, img-url=https://raw.githubusercontent.com/Orz-3/mini/master/Color/wechat.png, enabled=true

[mitm]
hostname = *.asia
