[rewrite_local]
# 1) 抓包重写: 微信或应用内打开邦邦赚接口抓取 Token
^https?:\/\/hd\.hnqlwlkj\.xyz\/g\/ url script-request-header https://raw.githubusercontent.com/5jwoj/BeRich/main/bangbangzhuan/bangbangzhuan_qx.js

[task_local]
# 2) 定时任务: 每天 8:30 自动上报广告看视频收益
30 8 * * * https://raw.githubusercontent.com/5jwoj/BeRich/main/bangbangzhuan/bangbangzhuan_qx.js, tag=邦邦赚, img-url=https://raw.githubusercontent.com/Orz-3/mini/master/Color/reward.png, enabled=true

[mitm]
hostname = hd.hnqlwlkj.xyz
